define(function() {

    // This is not a comprehensive list of country codes but just the subset used on metal-archives.com at the time of this writing.

    "use strict";

    return {
        "Afghanistan":"af",
        "Albania":"al",
        "Algeria":"dz",
        "Andorra":"ad",
        "Angola":"ao",
        "Argentina":"ar",
        "Armenia":"am",
        "Aruba":"aw",
        "Australia":"au",
        "Austria":"at",
        "Azerbaijan":"az",
        "Bahrain":"bh",
        "Bangladesh":"bd",
        "Barbados":"bb",
        "Belarus":"by",
        "Belgium":"be",
        "Belize":"bz",
        "Bolivia":"bo",
        "Bosnia and Herzegovina":"ba",
        "Botswana":"bw",
        "Brazil":"br",
        "Brunei":"bn",
        "Bulgaria":"bg",
        "Canada":"ca",
        "Chile":"cl",
        "China":"cn",
        "Colombia":"co",
        "Costa Rica":"cr",
        "Croatia":"hr",
        "Cuba":"cu",
        "Curaçao":"cw",
        "Cyprus":"cy",
        "Czech Republic":"cz",
        "Denmark":"dk",
        "Dominican Republic":"do",
        "Ecuador":"ec",
        "Egypt":"eg",
        "El Salvador":"sv",
        "Estonia":"ee",
        "Faroe Islands":"fo",
        "Finland":"fi",
        "France":"fr",
        "French Polynesia":"pf",
        "Georgia":"ge",
        "Germany":"de",
        "Gibraltar":"gi",
        "Greece":"gr",
        "Greenland":"gl",
        "Guam":"gu",
        "Guatemala":"gt",
        "Guyana":"gy",
        "Honduras":"hn",
        "Hungary":"hu",
        "Iceland":"is",
        "India":"in",
        "Indonesia":"id",
        "International":"xx",
        "Iran":"ir",
        "Iraq":"iq",
        "Ireland":"ie",
        "Israel":"il",
        "Italy":"it",
        "Jamaica":"jm",
        "Japan":"jp",
        "Jordan":"jo",
        "Kazakhstan":"kz",
        "Kenya":"ke",
        "Korea, South":"kr",
        "Kuwait":"kw",
        "Kyrgyzstan":"kg",
        "Laos":"la",
        "Latvia":"lv",
        "Lebanon":"lb",
        "Libya":"ly",
        "Liechtenstein":"li",
        "Lithuania":"lt",
        "Luxembourg":"lu",
        "Macedonia (FYROM)":"mk",
        "Madagascar":"mg",
        "Malaysia":"my",
        "Maldives":"mv",
        "Malta":"mt",
        "Mauritius":"mu",
        "Mexico":"mx",
        "Moldova":"md",
        "Monaco":"mc",
        "Mongolia":"mn",
        "Montenegro":"me",
        "Morocco":"ma",
        "Mozambique":"mz",
        "Myanmar":"mm",
        "Namibia":"na",
        "Nepal":"np",
        "Netherlands":"nl",
        "New Caledonia":"nc",
        "New Zealand":"nz",
        "Nicaragua":"ni",
        "Norway":"no",
        "Oman":"om",
        "Pakistan":"pk",
        "Panama":"pa",
        "Paraguay":"py",
        "Peru":"pe",
        "Philippines":"ph",
        "Poland":"pl",
        "Portugal":"pt",
        "Puerto Rico":"pr",
        "Qatar":"qa",
        "Reunion":"re",
        "Romania":"ro",
        "Russia":"ru",
        "San Marino":"sm",
        "Saudi Arabia":"sa",
        "Serbia":"rs",
        "Singapore":"sg",
        "Slovakia":"sk",
        "Slovenia":"si",
        "South Africa":"za",
        "Spain":"es",
        "Sri Lanka":"lk",
        "Suriname":"sr",
        "Sweden":"se",
        "Switzerland":"ch",
        "Syria":"sy",
        "Taiwan":"tw",
        "Tajikistan":"tj",
        "Thailand":"th",
        "Trinidad and Tobago":"tt",
        "Tunisia":"tn",
        "Turkey":"tr",
        "Turkmenistan":"tm",
        "Uganda":"ug",
        "Ukraine":"ua",
        "United Arab Emirates":"ae",
        "United Kingdom":"gb",
        "United States":"us",
        "Uruguay":"uy",
        "Uzbekistan":"uz",
        "Venezuela":"ve",
        "Vietnam":"vn"
    };
});